const PROPERTY_IMAGE_MAX_MB = 50;
const PROPERTY_DOCUMENT_MAX_MB = 50;
const PROPERTY_WALKTHROUGH_MAX_MB = 15;

module.exports = {
  PROPERTY_IMAGE_MAX_MB,
  PROPERTY_DOCUMENT_MAX_MB,
  PROPERTY_WALKTHROUGH_MAX_MB,
  PROPERTY_IMAGE_MAX_BYTES: PROPERTY_IMAGE_MAX_MB * 1024 * 1024,
  PROPERTY_DOCUMENT_MAX_BYTES: PROPERTY_DOCUMENT_MAX_MB * 1024 * 1024,
  PROPERTY_WALKTHROUGH_MAX_BYTES: PROPERTY_WALKTHROUGH_MAX_MB * 1024 * 1024,
};
